import type {
  EnemyConfig,
  GameMapConfig,
  TowerConfig,
  TowerTypeId,
} from '@/types/game';

export const BOARD_COLS = 10;
export const BOARD_ROWS = 7;
export const TILE_SIZE = 72;
export const STARTING_GOLD = 150;
export const STARTING_LIVES = 12;
export const INTEREST_RATE = 0.05;
export const CONTINUOUS_WAVE_DELAY_MS = 1600;
export const WAVE_CLEAR_BONUS_BASE = 22;
export const WAVE_CLEAR_BONUS_STEP = 5;

export const DEFAULT_MAP_ID = 'meadow-run';

export const GAME_MAPS: GameMapConfig[] = [
  {
    id: 'meadow-run',
    name: 'Meadow Run',
    tagline: 'Balanced',
    description: 'A gentle S-curve with good coverage for balanced kitten lineups.',
    cols: BOARD_COLS,
    rows: BOARD_ROWS,
    path: [
      { col: 0, row: 3 },
      { col: 1, row: 3 },
      { col: 2, row: 3 },
      { col: 2, row: 2 },
      { col: 2, row: 1 },
      { col: 3, row: 1 },
      { col: 4, row: 1 },
      { col: 5, row: 1 },
      { col: 5, row: 2 },
      { col: 5, row: 3 },
      { col: 6, row: 3 },
      { col: 7, row: 3 },
      { col: 7, row: 4 },
      { col: 7, row: 5 },
      { col: 8, row: 5 },
      { col: 9, row: 5 },
    ],
  },
  {
    id: 'creek-bend',
    name: 'Creek Bend',
    tagline: 'Long lane',
    description: 'A broader route with long straights that reward careful ranged placement.',
    cols: BOARD_COLS,
    rows: BOARD_ROWS,
    path: [
      { col: 0, row: 1 },
      { col: 1, row: 1 },
      { col: 2, row: 1 },
      { col: 3, row: 1 },
      { col: 3, row: 2 },
      { col: 3, row: 3 },
      { col: 2, row: 3 },
      { col: 1, row: 3 },
      { col: 1, row: 4 },
      { col: 1, row: 5 },
      { col: 2, row: 5 },
      { col: 3, row: 5 },
      { col: 4, row: 5 },
      { col: 5, row: 5 },
      { col: 6, row: 5 },
      { col: 7, row: 5 },
      { col: 8, row: 5 },
      { col: 9, row: 5 },
    ],
  },
  {
    id: 'orchard-loop',
    name: 'Orchard Loop',
    tagline: 'Tight turns',
    description: 'A compact looping approach that favors burst damage near the center.',
    cols: BOARD_COLS,
    rows: BOARD_ROWS,
    path: [
      { col: 0, row: 4 },
      { col: 1, row: 4 },
      { col: 2, row: 4 },
      { col: 3, row: 4 },
      { col: 3, row: 3 },
      { col: 3, row: 2 },
      { col: 4, row: 2 },
      { col: 5, row: 2 },
      { col: 6, row: 2 },
      { col: 6, row: 3 },
      { col: 6, row: 4 },
      { col: 5, row: 4 },
      { col: 4, row: 4 },
      { col: 4, row: 5 },
      { col: 5, row: 5 },
      { col: 6, row: 5 },
      { col: 7, row: 5 },
      { col: 8, row: 5 },
      { col: 9, row: 5 },
    ],
  },
];

export const MAPS_BY_ID = Object.fromEntries(GAME_MAPS.map((map) => [map.id, map])) as Record<
  GameMapConfig['id'],
  GameMapConfig
>;

export const TOWER_TYPES: Record<TowerTypeId, TowerConfig> = {
  archer: {
    id: 'archer',
    name: 'Archer Cat',
    cost: 50,
    range: 2.6,
    damage: 18,
    fireRateMs: 900,
    splashRadius: 0,
    accent: '#ffca7a',
    description: 'Balanced range and reliable bow shots.',
    spriteName: 'archer-cat',
    projectileVariant: 'orb',
    upgradeTree: [
      {
        id: 'archer-marksman',
        name: 'Marksman',
        description: 'Stretch the lane and sharpen each arrow.',
        parentId: null,
        cost: 40,
        range: 0.4,
        damage: 7,
        fireRateMs: -60,
        splashRadius: 0,
      },
      {
        id: 'archer-volley',
        name: 'Volley',
        description: 'Trade some reach for a much faster firing rhythm.',
        parentId: null,
        cost: 40,
        range: 0.2,
        damage: 5,
        fireRateMs: -140,
        splashRadius: 0,
      },
      {
        id: 'archer-deadeye',
        name: 'Deadeye',
        description: 'Longer aim and heavier single-shot pressure.',
        parentId: 'archer-marksman',
        cost: 70,
        range: 0.45,
        damage: 12,
        fireRateMs: -70,
        splashRadius: 0,
      },
      {
        id: 'archer-lanebreaker',
        name: 'Lanebreaker',
        description: 'Capstone reach for deleting dangerous targets early.',
        parentId: 'archer-deadeye',
        cost: 105,
        range: 0.55,
        damage: 18,
        fireRateMs: -90,
        splashRadius: 0,
      },
      {
        id: 'archer-splitshot',
        name: 'Split Shot',
        description: 'Leaner draw timing to overwhelm with tempo.',
        parentId: 'archer-volley',
        cost: 65,
        range: 0.2,
        damage: 8,
        fireRateMs: -140,
        splashRadius: 0,
      },
      {
        id: 'archer-arrowstorm',
        name: 'Arrowstorm',
        description: 'A relentless final form for sustained lane coverage.',
        parentId: 'archer-splitshot',
        cost: 95,
        range: 0.25,
        damage: 12,
        fireRateMs: -170,
        splashRadius: 0,
      },
    ],
  },
  claw: {
    id: 'claw',
    name: 'Claw Cat',
    cost: 75,
    range: 1.6,
    damage: 42,
    fireRateMs: 1250,
    splashRadius: 0,
    accent: '#ff8a80',
    description: 'Heavy swipes for rodents that get too close.',
    spriteName: 'claw-cat',
    projectileVariant: 'slash',
    upgradeTree: [
      {
        id: 'claw-stalker',
        name: 'Stalker',
        description: 'Sharper bursts for cats that live on the edge of the path.',
        parentId: null,
        cost: 55,
        range: 0.25,
        damage: 15,
        fireRateMs: -120,
        splashRadius: 0,
      },
      {
        id: 'claw-guardian',
        name: 'Guardian',
        description: 'Broader threat coverage with steadier swipes.',
        parentId: null,
        cost: 60,
        range: 0.35,
        damage: 10,
        fireRateMs: -80,
        splashRadius: 0,
      },
      {
        id: 'claw-frenzy',
        name: 'Frenzy',
        description: 'Shorter pauses between brutal multi-swipe bursts.',
        parentId: 'claw-stalker',
        cost: 85,
        range: 0.2,
        damage: 22,
        fireRateMs: -160,
        splashRadius: 0,
      },
      {
        id: 'claw-executioner',
        name: 'Executioner',
        description: 'A capstone path for melting anything that gets close.',
        parentId: 'claw-frenzy',
        cost: 120,
        range: 0.25,
        damage: 30,
        fireRateMs: -160,
        splashRadius: 0,
      },
      {
        id: 'claw-pouncer',
        name: 'Pouncer',
        description: 'Extra reach for catching runners earlier on corners.',
        parentId: 'claw-guardian',
        cost: 80,
        range: 0.35,
        damage: 14,
        fireRateMs: -110,
        splashRadius: 0,
      },
      {
        id: 'claw-mauler',
        name: 'Mauler',
        description: 'Late-game lane control with longer, heavier swipes.',
        parentId: 'claw-pouncer',
        cost: 115,
        range: 0.4,
        damage: 20,
        fireRateMs: -130,
        splashRadius: 0,
      },
    ],
  },
  magic: {
    id: 'magic',
    name: 'Magic Cat',
    cost: 100,
    range: 2.25,
    damage: 26,
    fireRateMs: 800,
    splashRadius: 0,
    accent: '#8be7ff',
    description: 'Slower arcane bolts that land with heavier impact.',
    spriteName: 'magic-cat',
    projectileVariant: 'bolt',
    upgradeTree: [
      {
        id: 'magic-stormcaller',
        name: 'Stormcaller',
        description: 'Lean into rapid, hard-hitting arcane pressure.',
        parentId: null,
        cost: 70,
        range: 0.25,
        damage: 12,
        fireRateMs: -100,
        splashRadius: 0,
      },
      {
        id: 'magic-hexweaver',
        name: 'Hexweaver',
        description: 'Favors longer reach and steadier control over pace.',
        parentId: null,
        cost: 75,
        range: 0.4,
        damage: 8,
        fireRateMs: -50,
        splashRadius: 0,
      },
      {
        id: 'magic-chainpulse',
        name: 'Chain Pulse',
        description: 'More force and tempo for collapsing dangerous packs.',
        parentId: 'magic-stormcaller',
        cost: 105,
        range: 0.2,
        damage: 18,
        fireRateMs: -120,
        splashRadius: 0,
      },
      {
        id: 'magic-celestiallance',
        name: 'Celestial Lance',
        description: 'A capstone burst path for devastating bolt strikes.',
        parentId: 'magic-chainpulse',
        cost: 145,
        range: 0.3,
        damage: 26,
        fireRateMs: -140,
        splashRadius: 0,
      },
      {
        id: 'magic-longcurse',
        name: 'Long Curse',
        description: 'Keeps arcane pressure on lanes from safer positions.',
        parentId: 'magic-hexweaver',
        cost: 100,
        range: 0.35,
        damage: 14,
        fireRateMs: -90,
        splashRadius: 0,
      },
      {
        id: 'magic-voidsigil',
        name: 'Void Sigil',
        description: 'Maximum lane reach without giving up heavy spell impact.',
        parentId: 'magic-longcurse',
        cost: 140,
        range: 0.4,
        damage: 22,
        fireRateMs: -100,
        splashRadius: 0,
      },
    ],
  },
  frost: {
    id: 'frost',
    name: 'Frost Cat',
    cost: 95,
    range: 2.4,
    damage: 10,
    fireRateMs: 1150,
    splashRadius: 0,
    accent: '#97e8ff',
    description: 'Icy spells slow rodents down and can lock whole packs in place.',
    spriteName: 'frost-cat',
    projectileVariant: 'frost',
    slowStrength: 0.45,
    slowDurationMs: 1100,
    chainCount: 0,
    chainRange: 0,
    upgradeTree: [
      {
        id: 'frost-deepfreeze',
        name: 'Deep Freeze',
        description: 'Lean into longer, harsher slows that nearly stop the lane.',
        parentId: null,
        cost: 65,
        range: 0.2,
        damage: 2,
        fireRateMs: -50,
        splashRadius: 0,
        slowStrength: 0.2,
        slowDurationMs: 350,
      },
      {
        id: 'frost-hailburst',
        name: 'Hail Burst',
        description: 'Trade some control for faster icy volleys and light area chill.',
        parentId: null,
        cost: 70,
        range: 0.15,
        damage: 5,
        fireRateMs: -110,
        splashRadius: 0.35,
        slowStrength: 0.1,
        slowDurationMs: 150,
      },
      {
        id: 'frost-coldsnap',
        name: 'Cold Snap',
        description: 'Build toward brief freezes that can stop dangerous runners cold.',
        parentId: 'frost-deepfreeze',
        cost: 95,
        range: 0.2,
        damage: 4,
        fireRateMs: -70,
        splashRadius: 0,
        slowStrength: 0.2,
        slowDurationMs: 350,
      },
      {
        id: 'frost-absolutewinter',
        name: 'Absolute Winter',
        description: 'A capstone freeze path that locks priority targets in place.',
        parentId: 'frost-coldsnap',
        cost: 135,
        range: 0.3,
        damage: 6,
        fireRateMs: -90,
        splashRadius: 0,
        slowStrength: 0.2,
        slowDurationMs: 450,
      },
      {
        id: 'frost-sleetdance',
        name: 'Sleet Dance',
        description: 'Broader hail patterns for controlling clustered enemy packs.',
        parentId: 'frost-hailburst',
        cost: 100,
        range: 0.2,
        damage: 7,
        fireRateMs: -120,
        splashRadius: 0.45,
        slowStrength: 0.05,
        slowDurationMs: 150,
      },
      {
        id: 'frost-whiteout',
        name: 'Whiteout',
        description: 'Late-wave area control with heavier hail and wider chill radius.',
        parentId: 'frost-sleetdance',
        cost: 140,
        range: 0.25,
        damage: 9,
        fireRateMs: -120,
        splashRadius: 0.55,
        slowStrength: 0.1,
        slowDurationMs: 200,
      },
    ],
  },
  storm: {
    id: 'storm',
    name: 'Storm Cat',
    cost: 130,
    range: 2.45,
    damage: 16,
    fireRateMs: 1100,
    splashRadius: 0,
    accent: '#c7ddff',
    description: 'Forking lightning leaps across crowded packs of rodents.',
    spriteName: 'storm-cat',
    projectileVariant: 'chain',
    slowStrength: 0,
    slowDurationMs: 0,
    chainCount: 2,
    chainRange: 1.45,
    upgradeTree: [
      {
        id: 'storm-tempest',
        name: 'Tempest',
        description: 'Increase jump count and cadence for swarm-clearing arcs.',
        parentId: null,
        cost: 80,
        range: 0.2,
        damage: 4,
        fireRateMs: -90,
        splashRadius: 0,
        chainCount: 1,
        chainRange: 0.2,
      },
      {
        id: 'storm-thunderhead',
        name: 'Thunderhead',
        description: 'Hit harder and stretch each lightning jump farther.',
        parentId: null,
        cost: 85,
        range: 0.25,
        damage: 8,
        fireRateMs: -40,
        splashRadius: 0,
        chainCount: 1,
        chainRange: 0.35,
      },
      {
        id: 'storm-arcweb',
        name: 'Arc Web',
        description: 'Weave lightning through thicker packs with extra jumps.',
        parentId: 'storm-tempest',
        cost: 115,
        range: 0.2,
        damage: 5,
        fireRateMs: -110,
        splashRadius: 0,
        chainCount: 1,
        chainRange: 0.25,
      },
      {
        id: 'storm-supercell',
        name: 'Supercell',
        description: 'Capstone crowd control with relentless high-density chaining.',
        parentId: 'storm-arcweb',
        cost: 155,
        range: 0.25,
        damage: 7,
        fireRateMs: -110,
        splashRadius: 0,
        chainCount: 1,
        chainRange: 0.25,
      },
      {
        id: 'storm-skyhammer',
        name: 'Skyhammer',
        description: 'Push the bolt into heavier chain strikes on tougher waves.',
        parentId: 'storm-thunderhead',
        cost: 120,
        range: 0.25,
        damage: 10,
        fireRateMs: -60,
        splashRadius: 0,
        chainCount: 1,
        chainRange: 0.3,
      },
      {
        id: 'storm-judgment',
        name: 'Judgment',
        description: 'A final storm path for brutal lightning chains and high burst.',
        parentId: 'storm-skyhammer',
        cost: 160,
        range: 0.3,
        damage: 14,
        fireRateMs: -70,
        splashRadius: 0,
        chainCount: 1,
        chainRange: 0.35,
      },
    ],
  },
  bombardier: {
    id: 'bombardier',
    name: 'Bombardier Cat',
    cost: 120,
    range: 2.35,
    damage: 24,
    fireRateMs: 1300,
    splashRadius: 1.05,
    accent: '#ffd36e',
    description: 'Lobs explosive yarn bombs that punish clustered rodents.',
    spriteName: 'bombardier-cat',
    projectileVariant: 'bomb',
    upgradeTree: [
      {
        id: 'bombardier-siegefuse',
        name: 'Siege Fuse',
        description: 'Heavier bombs with a wider crater around the blast.',
        parentId: null,
        cost: 85,
        range: 0.2,
        damage: 10,
        fireRateMs: -90,
        splashRadius: 0.3,
      },
      {
        id: 'bombardier-shrapnelpack',
        name: 'Shrapnel Pack',
        description: 'Spread the pain across bigger clusters with broader splash.',
        parentId: null,
        cost: 90,
        range: 0.15,
        damage: 8,
        fireRateMs: -60,
        splashRadius: 0.45,
      },
      {
        id: 'bombardier-cratermaker',
        name: 'Crater Maker',
        description: 'Push the siege path into punishing area denial.',
        parentId: 'bombardier-siegefuse',
        cost: 125,
        range: 0.25,
        damage: 16,
        fireRateMs: -110,
        splashRadius: 0.4,
      },
      {
        id: 'bombardier-moonshotmortar',
        name: 'Moonshot Mortar',
        description: 'Capstone bombardment with huge blast radius and reach.',
        parentId: 'bombardier-cratermaker',
        cost: 170,
        range: 0.4,
        damage: 22,
        fireRateMs: -110,
        splashRadius: 0.45,
      },
      {
        id: 'bombardier-emberburst',
        name: 'Ember Burst',
        description: 'Higher cadence plus broader fragments for crowd cleaning.',
        parentId: 'bombardier-shrapnelpack',
        cost: 120,
        range: 0.2,
        damage: 12,
        fireRateMs: -100,
        splashRadius: 0.5,
      },
      {
        id: 'bombardier-clusteryarn',
        name: 'Cluster Yarn',
        description: 'A final shrapnel path for massive late-wave pack control.',
        parentId: 'bombardier-emberburst',
        cost: 160,
        range: 0.25,
        damage: 16,
        fireRateMs: -130,
        splashRadius: 0.6,
      },
    ],
  },
};

export const ENEMY_TYPES: Record<string, EnemyConfig> = {
  mouse: {
    id: 'mouse',
    name: 'Mouse',
    baseHp: 50,
    speed: 0.88,
    reward: 3,
    damage: 1,
    tint: '#f7f1e1',
    spriteName: 'mouse',
  },
  rat: {
    id: 'rat',
    name: 'Rat',
    baseHp: 90,
    speed: 0.72,
    reward: 5,
    damage: 1,
    tint: '#c1a48d',
    spriteName: 'rat',
  },
  brute: {
    id: 'brute',
    name: 'Boss Rat',
    baseHp: 220,
    speed: 0.58,
    reward: 16,
    damage: 2,
    tint: '#7b5e57',
    spriteName: 'brute-rat',
  },
};
